generate cnid=.
replace cnid=1 if country=="Afghanistan"
replace cnid=2 if country=="Albania"
replace cnid=3 if country=="Algeria"
replace cnid=4 if country=="Andorra"
replace cnid=5 if country=="Angola"
replace cnid=6 if country=="Anguilla"
replace cnid=7 if country=="Antigua and Barbuda"
replace cnid=8 if country=="Argentina"
replace cnid=9 if country=="Armenia"
replace cnid=10 if country=="Aruba"
replace cnid=11 if country=="Australia"
replace cnid=12 if country=="Austria"
replace cnid=13 if country=="Azerbaijan"
replace cnid=14 if country=="Bahamas, The"
replace cnid=15 if country=="Bahrain"
replace cnid=16 if country=="Bangladesh"
replace cnid=17 if country=="Barbados"
replace cnid=18 if country=="Belarus"
replace cnid=19 if country=="Belgium"
replace cnid=20 if country=="Belize"
replace cnid=21 if country=="Benin"
replace cnid=22 if country=="Bermuda"
replace cnid=23 if country=="Bhutan"
replace cnid=24 if country=="Bolivia"
replace cnid=25 if country=="Bosnia and Herzegovina"
replace cnid=26 if country=="Botswana"
replace cnid=27 if country=="Brazil"
replace cnid=28 if country=="Brunei Darussalam"
replace cnid=29 if country=="Bulgaria"
replace cnid=30 if country=="Burkina Faso"
replace cnid=31 if country=="Burundi"
replace cnid=32 if country=="Cabo Verde"
replace cnid=33 if country=="Cambodia"
replace cnid=34 if country=="Cameroon"
replace cnid=35 if country=="Canada"
replace cnid=36 if country=="Cayman Islands"
replace cnid=37 if country=="Central African Republic"
replace cnid=38 if country=="Chad"
replace cnid=39 if country=="Channel Islands"
replace cnid=40 if country=="Chile"
replace cnid=41 if country=="China"
replace cnid=42 if country=="Colombia"
replace cnid=43 if country=="Comoros"
replace cnid=44 if country=="Congo, Rep." /*Republic Congo*/
replace cnid=45 if country=="Congo, Dem. Rep." /*DRC*/
replace cnid=46 if country=="Costa Rica"
replace cnid=47 if country=="Cote d'Ivoire"
replace cnid=48 if country=="Croatia"
replace cnid=49 if country=="Cuba"
replace cnid=50 if country=="Czechoslovakia"
replace cnid=51 if country=="Cyprus"
replace cnid=52 if country=="Czechia"
replace cnid=53 if country=="Denmark"
replace cnid=54 if country=="Djibouti"
replace cnid=55 if country=="Dominica"
replace cnid=56 if country=="Dominican Republic"
replace cnid=57 if country=="Ecuador"
replace cnid=58 if country=="Egypt, Arab Rep."
replace cnid=59 if country=="El Salvador"
replace cnid=60 if country=="Equatorial Guinea"
replace cnid=61 if country=="Eritrea"
replace cnid=62 if country=="Estonia"
replace cnid=63 if country=="Ethiopia"
replace cnid=64 if country=="Faroe Islands"
replace cnid=65 if country=="Fiji"
replace cnid=66 if country=="Finland"
replace cnid=67 if country=="France"
replace cnid=68 if country=="French Polynesia"
replace cnid=69 if country=="Gabon"
replace cnid=70 if country=="Gambia, The"
replace cnid=71 if country=="Georgia"
replace cnid=72 if country=="Germany"
replace cnid=73 if country=="Ghana"
replace cnid=74 if country=="Greece"
replace cnid=75 if country=="Greenland"
replace cnid=76 if country=="Grenada"
replace cnid=77 if country=="Guam"
replace cnid=78 if country=="Guatemala"
replace cnid=79 if country=="Guinea"
replace cnid=80 if country=="Guinea-Bissau"
replace cnid=81 if country=="Guyana"
replace cnid=82 if country=="Haiti"
replace cnid=83 if country=="Honduras"
replace cnid=84 if country=="Hong Kong SAR, China"
replace cnid=85 if country=="Hungary"
replace cnid=86 if country=="Iceland"
replace cnid=87 if country=="India"
replace cnid=88 if country=="Indonesia"
replace cnid=89 if country=="Iran, Islamic Rep."
replace cnid=90 if country=="Iraq"
replace cnid=91 if country=="Ireland"
replace cnid=92 if country=="Isle of Man"
replace cnid=93 if country=="Israel"
replace cnid=94 if country=="Italy"
replace cnid=95 if country=="Jamaica"
replace cnid=96 if country=="Japan"
replace cnid=97 if country=="Jordan"
replace cnid=98 if country=="Kazakhstan"
replace cnid=99 if country=="Kenya"
replace cnid=100 if country=="Kiribati"
replace cnid=101 if country=="Korea, Dem. People's Rep." /*North Korea*/
replace cnid=102 if country=="Korea, Rep." /*South Korea*/
replace cnid=103 if country=="Kosovo"
replace cnid=104 if country=="Kuwait"
replace cnid=105 if country=="Kyrgyz Republic"
replace cnid=106 if country=="Lao PDR"
replace cnid=107 if country=="Latvia"
replace cnid=108 if country=="Lebanon"
replace cnid=109 if country=="Lesotho"
replace cnid=110 if country=="Liberia"
replace cnid=111 if country=="Libya"
replace cnid=112 if country=="Liechtenstein"
replace cnid=113 if country=="Lithuania"
replace cnid=114 if country=="Luxembourg"
replace cnid=115 if country=="Macao SAR, China"
replace cnid=116 if country=="North Macedonia"
replace cnid=117 if country=="Madagascar"
replace cnid=118 if country=="Malawi"
replace cnid=119 if country=="Malaysia"
replace cnid=120 if country=="Maldives"
replace cnid=121 if country=="Mali"
replace cnid=122 if country=="Malta"
replace cnid=123 if country=="Marshall Islands"
replace cnid=124 if country=="Mauritania"
replace cnid=125 if country=="Mauritius"
replace cnid=126 if country=="Mexico"
replace cnid=127 if country=="Micronesia, Fed. Sts."
replace cnid=128 if country=="Moldova"
replace cnid=129 if country=="Monaco"
replace cnid=130 if country=="Mongolia"
replace cnid=131 if country=="Montenegro"
replace cnid=132 if country=="Morocco"
replace cnid=133 if country=="Mozambique"
replace cnid=134 if country=="Myanmar"
replace cnid=135 if country=="Namibia"
replace cnid=136 if country=="Nepal"
replace cnid=137 if country=="Netherlands"
replace cnid=138 if country=="New Caledonia"
replace cnid=139 if country=="New Zealand"
replace cnid=140 if country=="Nicaragua"
replace cnid=141 if country=="Niger"
replace cnid=142 if country=="Nigeria"
replace cnid=143 if country=="Northern Mariana Islands"
replace cnid=144 if country=="Norway"
replace cnid=145 if country=="Oman"
replace cnid=146 if country=="Pakistan"
replace cnid=147 if country=="Palau"
replace cnid=148 if country=="Panama"
replace cnid=149 if country=="Papua New Guinea"
replace cnid=150 if country=="Paraguay"
replace cnid=151 if country=="Peru"
replace cnid=152 if country=="Philippines"
replace cnid=153 if country=="Poland"
replace cnid=154 if country=="Portugal"
replace cnid=155 if country=="Puerto Rico"
replace cnid=156 if country=="Qatar"
replace cnid=157 if country=="Romania"
replace cnid=158 if country=="Russian Federation"
replace cnid=159 if country=="Rwanda"
replace cnid=160 if country=="American Samoa"
replace cnid=161 if country=="San Marino"
replace cnid=162 if country=="Sao Tome and Principe"
replace cnid=163 if country=="Saudi Arabia"
replace cnid=164 if country=="Senegal"
replace cnid=165 if country=="Serbia"
replace cnid=166 if country=="Seychelles"
replace cnid=167 if country=="Sierra Leone"
replace cnid=168 if country=="Singapore"
replace cnid=169 if country=="Sint Maarten (Dutch part)"
replace cnid=170 if country=="Slovak Republic"
replace cnid=171 if country=="Slovenia"
replace cnid=172 if country=="Solomon Islands"
replace cnid=173 if country=="Somalia"
replace cnid=174 if country=="South Africa"
replace cnid=175 if country=="South Sudan"
replace cnid=176 if country=="Spain"
replace cnid=177 if country=="Sri Lanka"
replace cnid=178 if country=="St. Kitts and Nevis"
replace cnid=179 if country=="St. Lucia"
replace cnid=180 if country=="St. Martin (French part)"
replace cnid=181 if country=="St. Vincent and the Grenadines"
replace cnid=182 if country=="Sudan"
replace cnid=183 if country=="Suriname"
replace cnid=184 if country=="Eswatini" /*Swaziland*/
replace cnid=185 if country=="Sweden"
replace cnid=186 if country=="Switzerland"
replace cnid=187 if country=="Syrian Arab Republic"
replace cnid=188 if country=="Taiwan"
replace cnid=189 if country=="Tajikistan"
replace cnid=190 if country=="Tanzania"
replace cnid=191 if country=="Thailand"
replace cnid=192 if country=="Timor-Leste"
replace cnid=193 if country=="Togo"
replace cnid=194 if country=="Tonga"
replace cnid=195 if country=="Trinidad and Tobago"
replace cnid=196 if country=="Tunisia"
replace cnid=197 if country=="Turkiye"
replace cnid=198 if country=="Turkmenistan"
replace cnid=199 if country=="Turks and Caicos Islands"
replace cnid=200 if country=="Tuvalu"
replace cnid=201 if country=="Uganda"
replace cnid=202 if country=="Ukraine"
replace cnid=203 if country=="United Arab Emirates"
replace cnid=204 if country=="United Kingdom"
replace cnid=205 if country=="United States"
replace cnid=206 if country=="Uruguay"
replace cnid=207 if country=="Uzbekistan"
replace cnid=208 if country=="Vanuatu"
replace cnid=209 if country=="Venezuela, RB"
replace cnid=210 if country=="Viet Nam"
replace cnid=211 if country=="Virgin Islands (U.S.)"
replace cnid=212 if country=="West Bank and Gaza" /* Palestinian Territories*/
replace cnid=213 if country=="Yemen, Rep."
replace cnid=214 if country=="Zambia"
replace cnid=215 if country=="Zimbabwe"


/* Yugoslavia, Soviet Union*/

